name: LinkGrabber

on:
  schedule:
    - cron: '0 */3 * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      with:
      token: ${{ secrets.ACCESS_TOKEN }}

      - name: Grab Link

        run: |
          git config user.name "daanand"
          git config user.email "your-email@example.com"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add -A
          git commit -m "./youtubeLink.txt is updated."
          git push
          
